@echo off
set classespath=classes
set classespath=%classespath%;3rdparty\spring-aop-3.0.2.RELEASE.jar
set classespath=%classespath%;3rdparty\aopalliance-1.0.jar
set classespath=%classespath%;3rdparty\spring-asm-3.0.2.RELEASE.jar
set classespath=%classespath%;3rdparty\spring-beans-3.0.2.RELEASE.jar
set classespath=%classespath%;3rdparty\spring-core-3.0.2.RELEASE.jar
set classespath=%classespath%;3rdparty\commons-logging-1.1.1.jar
set classespath=%classespath%;3rdparty\aspectjweaver-1.6.6.jar
set classespath=%classespath%;3rdparty\cglib-nodep-2.2.jar
set classespath=%classespath%;3rdparty\jsr250-api-1.0.jar
set classespath=%classespath%;3rdparty\hibernate-core-3.3.2.GA.jar
set classespath=%classespath%;3rdparty\antlr-2.7.6.jar
set classespath=%classespath%;3rdparty\commons-collections-3.2.1.jar
set classespath=%classespath%;3rdparty\dom4j-1.6.1.jar
set classespath=%classespath%;3rdparty\xml-apis-1.0.b2.jar
set classespath=%classespath%;3rdparty\jta-1.1.jar
set classespath=%classespath%;3rdparty\slf4j-api-1.5.10.jar
set classespath=%classespath%;3rdparty\hibernate-annotations-3.4.0.GA.jar
set classespath=%classespath%;3rdparty\ejb3-persistence-1.0.2.GA.jar
set classespath=%classespath%;3rdparty\hibernate-commons-annotations-3.1.0.GA.jar
set classespath=%classespath%;3rdparty\hibernate-ehcache-3.3.2.GA.jar
set classespath=%classespath%;3rdparty\ehcache-1.6.2.jar
set classespath=%classespath%;3rdparty\javassist-3.11.0.GA.jar
set classespath=%classespath%;3rdparty\spring-orm-3.0.2.RELEASE.jar
set classespath=%classespath%;3rdparty\spring-jdbc-3.0.2.RELEASE.jar
set classespath=%classespath%;3rdparty\spring-tx-3.0.2.RELEASE.jar
set classespath=%classespath%;3rdparty\spring-context-3.0.2.RELEASE.jar
set classespath=%classespath%;3rdparty\spring-expression-3.0.2.RELEASE.jar
set classespath=%classespath%;3rdparty\commons-dbcp-1.2.2.jar
set classespath=%classespath%;3rdparty\commons-pool-1.3.jar
set classespath=%classespath%;3rdparty\h2-1.1.119.jar
set classespath=%classespath%;3rdparty\slf4j-log4j12-1.5.10.jar
set classespath=%classespath%;3rdparty\log4j-1.2.15.jar
set classespath=%classespath%;3rdparty\ehcache-jgroupsreplication-1.3.jar
set classespath=%classespath%;3rdparty\jgroups-2.6.8.GA.jar
set classespath=%classespath%;3rdparty\dozer-5.1.jar
set classespath=%classespath%;3rdparty\commons-beanutils-1.8.2.jar
set classespath=%classespath%;3rdparty\commons-lang-2.4.jar
set classespath=%classespath%;3rdparty\bsh-2.0b4.jar
set classespath=%classespath%;3rdparty\freemarker-2.3.16.jar
set classespath=%classespath%;3rdparty\swt-win32-x86-3.5.2.jar

start javaw -cp %classespath% com.navy.docman.DocMan
echo on
