copy "%USERPROFILE%\.m2\repository\org\springframework\spring-aop\3.0.2.RELEASE\spring-aop-3.0.2.RELEASE.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\aopalliance\aopalliance\1.0\aopalliance-1.0.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\springframework\spring-asm\3.0.2.RELEASE\spring-asm-3.0.2.RELEASE.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\springframework\spring-beans\3.0.2.RELEASE\spring-beans-3.0.2.RELEASE.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\springframework\spring-core\3.0.2.RELEASE\spring-core-3.0.2.RELEASE.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\commons-logging\commons-logging\1.1.1\commons-logging-1.1.1.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\aspectj\aspectjweaver\1.6.6\aspectjweaver-1.6.6.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\cglib\cglib-nodep\2.2\cglib-nodep-2.2.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\javax\annotation\jsr250-api\1.0\jsr250-api-1.0.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\hibernate\hibernate-core\3.3.2.GA\hibernate-core-3.3.2.GA.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\antlr\antlr\2.7.6\antlr-2.7.6.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\xml-apis\xml-apis\1.0.b2\xml-apis-1.0.b2.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\javax\transaction\jta\1.1\jta-1.1.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\slf4j\slf4j-api\1.5.10\slf4j-api-1.5.10.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\hibernate\hibernate-annotations\3.4.0.GA\hibernate-annotations-3.4.0.GA.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\hibernate\ejb3-persistence\1.0.2.GA\ejb3-persistence-1.0.2.GA.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\hibernate\hibernate-commons-annotations\3.1.0.GA\hibernate-commons-annotations-3.1.0.GA.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\hibernate\hibernate-ehcache\3.3.2.GA\hibernate-ehcache-3.3.2.GA.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\net\sf\ehcache\ehcache\1.6.2\ehcache-1.6.2.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\javassist\javassist\3.11.0.GA\javassist-3.11.0.GA.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\springframework\spring-orm\3.0.2.RELEASE\spring-orm-3.0.2.RELEASE.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\springframework\spring-jdbc\3.0.2.RELEASE\spring-jdbc-3.0.2.RELEASE.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\springframework\spring-tx\3.0.2.RELEASE\spring-tx-3.0.2.RELEASE.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\springframework\spring-context\3.0.2.RELEASE\spring-context-3.0.2.RELEASE.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\springframework\spring-expression\3.0.2.RELEASE\spring-expression-3.0.2.RELEASE.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\commons-dbcp\commons-dbcp\1.2.2\commons-dbcp-1.2.2.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\commons-pool\commons-pool\1.3\commons-pool-1.3.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\com\h2database\h2\1.1.119\h2-1.1.119.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\slf4j\slf4j-log4j12\1.5.10\slf4j-log4j12-1.5.10.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\log4j\log4j\1.2.15\log4j-1.2.15.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\net\sf\ehcache\ehcache-jgroupsreplication\1.3\ehcache-jgroupsreplication-1.3.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\jgroups\jgroups\2.6.8.GA\jgroups-2.6.8.GA.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\net\sf\dozer\dozer\5.1\dozer-5.1.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\commons-beanutils\commons-beanutils\1.8.2\commons-beanutils-1.8.2.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\commons-lang\commons-lang\2.4\commons-lang-2.4.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\beanshell\bsh\2.0b4\bsh-2.0b4.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\freemarker\freemarker\2.3.16\freemarker-2.3.16.jar" target\3rdparty
copy "%USERPROFILE%\.m2\repository\org\eclipse\swt-win32-x86\3.5.2\swt-win32-x86-3.5.2.jar" target\3rdparty

